/*
 * Copyright © 2022 CUI-OpenSource-Software (info@cuioss.de)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.cuioss.sheriff.token.client.dpop;

import org.jspecify.annotations.Nullable;

import java.util.Map;
import java.util.Objects;

/**
 * Applies a sender-constraint to an outgoing back-channel token request ({@code CLIENT-11}).
 * <p>
 * Two mechanisms are supported:
 * <ul>
 *   <li><strong>DPoP</strong> (RFC 9449): a per-request proof JWT is generated by a
 *       {@link DpopProofGenerator} and added as the {@code DPoP} request header, so the issued token
 *       is bound to the proof key via {@code cnf.jkt}.</li>
 *   <li><strong>mTLS</strong> (RFC 8705): the client certificate is presented at the TLS layer
 *       through the {@code HttpHandler} SSL context, so the token is bound to the certificate via
 *       {@code cnf."x5t#S256"}. No request header is added — the binding is transport-level.</li>
 * </ul>
 * Either way the resulting {@link ConstraintBinding} is recorded ({@link #binding()}) so the
 * sender-constraint can be preserved alongside the stored token (consumed by the token lifecycle,
 * {@code CLIENT-18}).
 *
 * @since 1.0
 * @author Oliver Wolff
 * @see <a href="https://www.rfc-editor.org/rfc/rfc9449">RFC 9449 - OAuth 2.0 DPoP</a>
 * @see <a href="https://www.rfc-editor.org/rfc/rfc8705">RFC 8705 - Mutual-TLS Certificate-Bound Access Tokens</a>
 */
public final class SenderConstraint {

    /** The RFC 9449 request header carrying the DPoP proof. */
    static final String DPOP_HEADER = "DPoP";

    private final DpopProofGenerator dpopGenerator;
    private final ConstraintBinding binding;

    private SenderConstraint(DpopProofGenerator dpopGenerator, ConstraintBinding binding) {
        this.dpopGenerator = dpopGenerator;
        this.binding = binding;
    }

    /**
     * Creates a DPoP sender-constraint driven by the given proof generator.
     *
     * @param generator the DPoP proof generator; must not be {@code null}
     * @return a DPoP sender-constraint whose binding confirms the generator's {@code jkt}
     */
    public static SenderConstraint dpop(DpopProofGenerator generator) {
        Objects.requireNonNull(generator, "generator must not be null");
        return new SenderConstraint(generator, ConstraintBinding.dpop(generator.jkt()));
    }

    /**
     * Creates a certificate-bound mTLS sender-constraint. The certificate itself is presented by the
     * {@code HttpHandler} SSL context; this constraint only records the resulting binding.
     *
     * @param certificateThumbprint the base64url-encoded SHA-256 certificate thumbprint; must not be
     *                              {@code null} or blank
     * @return an mTLS sender-constraint whose binding confirms the certificate thumbprint
     */
    public static SenderConstraint mtls(String certificateThumbprint) {
        return new SenderConstraint(null, ConstraintBinding.mtls(certificateThumbprint));
    }

    /**
     * Applies the sender-constraint to a token-endpoint request. For DPoP this adds the {@code DPoP}
     * proof header; for mTLS the binding is transport-level and no header is added.
     *
     * @param htm            the request HTTP method (e.g. {@code POST}); must not be {@code null} or blank
     * @param htu            the request URI (e.g. the token endpoint); must not be {@code null} or blank
     * @param requestHeaders the mutable request headers to decorate; must not be {@code null}
     */
    public void apply(String htm, String htu, Map<String, String> requestHeaders) {
        apply(htm, htu, null, requestHeaders);
    }

    /**
     * Applies the sender-constraint to a token-endpoint request, echoing a server-supplied
     * {@code DPoP-Nonce} when the authorization server challenged the previous attempt with
     * {@code use_dpop_nonce} (RFC 9449 §8). For mTLS no header is added and the nonce is irrelevant.
     *
     * @param htm            the request HTTP method; must not be {@code null} or blank
     * @param htu            the request URI; must not be {@code null} or blank
     * @param nonce          the server-provided DPoP nonce to echo, or {@code null} when none was challenged
     * @param requestHeaders the mutable request headers to decorate; must not be {@code null}
     */
    public void apply(String htm, String htu, @Nullable String nonce, Map<String, String> requestHeaders) {
        Objects.requireNonNull(requestHeaders, "requestHeaders must not be null");
        if (dpopGenerator != null) {
            requestHeaders.put(DPOP_HEADER, dpopGenerator.generateProof(htm, htu, nonce, null));
        }
    }

    /**
     * Applies the sender-constraint to a protected-resource request (e.g. userinfo), binding the proof
     * to the presented access token via the {@code ath} claim (RFC 9449 §4.3). For mTLS no header is
     * added and the binding is transport-level.
     *
     * @param htm            the request HTTP method; must not be {@code null} or blank
     * @param htu            the request URI; must not be {@code null} or blank
     * @param accessToken    the access token whose {@code ath} hash the proof carries; must not be
     *                       {@code null} or blank
     * @param nonce          the server-provided DPoP nonce to echo, or {@code null} when none was challenged
     * @param requestHeaders the mutable request headers to decorate; must not be {@code null}
     */
    public void applyProtectedResource(String htm, String htu, String accessToken, @Nullable String nonce,
            Map<String, String> requestHeaders) {
        Objects.requireNonNull(accessToken, "accessToken must not be null");
        Objects.requireNonNull(requestHeaders, "requestHeaders must not be null");
        if (accessToken.isBlank()) {
            throw new IllegalArgumentException("accessToken must not be blank");
        }
        if (dpopGenerator != null) {
            requestHeaders.put(DPOP_HEADER, dpopGenerator.generateProof(htm, htu, nonce, accessToken));
        }
    }

    /**
     * @return the HTTP {@code Authorization} scheme a protected-resource request must present when
     *         carrying a token bound by this constraint: {@code DPoP} for a DPoP-bound token, otherwise
     *         {@code Bearer} (mTLS binds at the TLS layer and presents the token as a Bearer credential)
     */
    public String authorizationScheme() {
        return binding.method() == ConstraintBinding.Method.DPOP ? "DPoP" : "Bearer";
    }

    /**
     * @return the recorded sender-constraint binding
     */
    public ConstraintBinding binding() {
        return binding;
    }

    /**
     * @return the sender-constraining method (DPoP or mTLS)
     */
    public ConstraintBinding.Method method() {
        return binding.method();
    }
}
