#!/bin/bash
# Zitadel Post-Startup Configuration Script
#
# Creates a service account with client_credentials for JWT access token acquisition.
# Unlike Keycloak (realm JSON import), Zitadel requires imperative API calls.
#
# Outputs:
#   - target/zitadel-credentials.properties (consumed by TestRealm.createZitadelProvider())

set -e

ZITADEL_URL="http://localhost:3080"
ZITADEL_HOST="zitadel:3080"
PAT_FILE="${PAT_FILE:-/tmp/zitadel-admin-pat/zitadel-admin-sa.pat}"
OUTPUT_DIR="${OUTPUT_DIR:-.}"
OUTPUT_FILE="${OUTPUT_DIR}/target/zitadel-credentials.properties"

# Load admin PAT
echo "Waiting for Zitadel admin PAT..."
for i in $(seq 1 30); do
    if [ -f "$PAT_FILE" ] && [ -s "$PAT_FILE" ]; then
        ADMIN_PAT=$(cat "$PAT_FILE")
        echo "Admin PAT loaded."
        break
    fi
    [ "$i" -eq 30 ] && echo "ERROR: PAT not found at $PAT_FILE" && exit 1
    sleep 1
done

# Helpers
zitadel_api() {
    local method="$1" path="$2" data="$3"
    if [ -n "$data" ]; then
        curl -s -X "$method" "${ZITADEL_URL}${path}" \
            -H "Host: ${ZITADEL_HOST}" \
            -H "Authorization: Bearer ${ADMIN_PAT}" \
            -H "Content-Type: application/json" -d "$data"
    else
        curl -s -X "$method" "${ZITADEL_URL}${path}" \
            -H "Host: ${ZITADEL_HOST}" \
            -H "Authorization: Bearer ${ADMIN_PAT}" \
            -H "Content-Type: application/json"
    fi
}
json_field() { python3 -c "import sys,json; print(json.load(sys.stdin)['$1'])" 2>/dev/null; }

echo "=== Configuring Zitadel for Integration Testing ==="

# Wait for management API (lags behind /debug/ready) — retry first real call
echo "Creating project..."
for i in $(seq 1 30); do
    PROJECT_ID=$(zitadel_api POST /management/v1/projects '{"name":"integration-test"}' 2>/dev/null | json_field id)
    [ -n "$PROJECT_ID" ] && break
    [ "$i" -eq 30 ] && echo "ERROR: Management API not ready after 30s" && exit 1
    sleep 1
done
echo "  Project: $PROJECT_ID"

# Create service account (machine user) with JWT access token type
echo "Creating service account..."
SERVICE_USER_ID=$(zitadel_api POST "/management/v1/users/machine" '{
    "userName": "zitadel-service",
    "name": "Service Account",
    "accessTokenType": "ACCESS_TOKEN_TYPE_JWT"
}' | json_field userId)
[ -z "$SERVICE_USER_ID" ] && echo "ERROR: Failed to create service account" && exit 1
echo "  Service user: $SERVICE_USER_ID"

# Generate client secret (client_id = userName, not numeric ID)
echo "Generating client secret..."
SECRET_RESPONSE=$(zitadel_api PUT "/management/v1/users/${SERVICE_USER_ID}/secret")
SERVICE_CLIENT_ID=$(echo "$SECRET_RESPONSE" | json_field clientId)
SERVICE_SECRET=$(echo "$SECRET_RESPONSE" | json_field clientSecret)
[ -z "$SERVICE_SECRET" ] && echo "ERROR: Failed to generate secret" && exit 1
echo "  Client ID: $SERVICE_CLIENT_ID"

# Enable oidcTokenExchange feature (may be useful for future roles/groups support)
zitadel_api PUT "/v2beta/features/instance" '{"oidcTokenExchange": true}' > /dev/null 2>&1 || true

# Write credentials
mkdir -p "$(dirname "$OUTPUT_FILE")"
cat > "$OUTPUT_FILE" << EOF
# Zitadel credentials (generated by setup.sh)
zitadel.service.client-id=${SERVICE_CLIENT_ID}
zitadel.service.client-secret=${SERVICE_SECRET}
zitadel.project.id=${PROJECT_ID}
EOF

echo "=== Zitadel ready: $SERVICE_CLIENT_ID ==="
