/*
 * Copyright © 2025 CUI-OpenSource-Software (info@cuioss.de)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.cuioss.sheriff.oauth.integration;

import de.cuioss.sheriff.oauth.integration.security.DpopProofHelper;
import de.cuioss.sheriff.oauth.integration.token.RopcStrategy;
import de.cuioss.sheriff.oauth.integration.token.TokenAcquisitionStrategy;
import de.cuioss.sheriff.oauth.integration.token.TokenExchangeStrategy;
import io.restassured.response.Response;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.EnumSet;
import java.util.Map;
import java.util.Properties;
import java.util.Set;

import static io.restassured.RestAssured.given;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Configuration and token acquisition for a single OIDC provider/realm.
 * <p>
 * Each instance encapsulates connection details, credentials, and declared
 * {@link Capability capabilities}. Factory methods create pre-configured
 * instances for each supported provider.
 * <p>
 * Adding a new IDP requires:
 * <ol>
 *     <li>A factory method here (connection details + capabilities)</li>
 *     <li>A registration entry in {@link TestProviders} (system property + factory)</li>
 *     <li>Issuer config in {@code application.properties} (with {@code %profile.} prefix)</li>
 *     <li>Docker service in {@code docker-compose.yml} (with compose profile)</li>
 * </ol>
 */
public class TestRealm {

    /**
     * Capabilities that an OIDC provider/realm may support. Tests use these to
     * declare which features they require — providers missing the required
     * capabilities are skipped with an INFO log, not silently hidden.
     */
    public enum Capability {
        /** Supports {@code offline_access} scope for refresh tokens. */
        OFFLINE_ACCESS,
        /** Token contains role claims usable for bearer auth. */
        ROLES,
        /** Token contains group claims usable for bearer auth. */
        GROUPS,
        /** Supports custom scopes beyond {@code openid profile email} (e.g. "read"). */
        CUSTOM_SCOPES,
        /** Access tokens are JWTs (not opaque). Required for access token validation tests. */
        JWT_ACCESS_TOKENS
    }

    // Keycloak connection constants
    private static final String KEYCLOAK_BASE_URL = "https://localhost:1443";
    private static final String TOKEN_ENDPOINT_TEMPLATE = "/realms/%s/protocol/openid-connect/token";

    // Integration realm constants
    private static final String INTEGRATION_REALM_ID = "integration";
    private static final String INTEGRATION_CLIENT_ID = "integration-client";
    private static final String INTEGRATION_CLIENT_SECRET = "integration-secret";
    private static final String INTEGRATION_USERNAME = "integration-user";
    private static final String INTEGRATION_PASSWORD = "integration-password";

    // DPoP client constants (same realm, different client with dpop.bound.access.tokens=true)
    private static final String DPOP_CLIENT_ID = "dpop-client";
    private static final String DPOP_CLIENT_SECRET = "dpop-secret";

    // JWE client constants (same realm, client with id_token_encrypted_response_alg/enc)
    private static final String JWE_CLIENT_ID = "jwe-client";
    private static final String JWE_CLIENT_SECRET = "jwe-secret";

    // Benchmark realm constants
    private static final String BENCHMARK_REALM_ID = "benchmark";
    private static final String BENCHMARK_CLIENT_ID = "benchmark-client";
    private static final String BENCHMARK_CLIENT_SECRET = "benchmark-secret";
    private static final String BENCHMARK_USERNAME = "benchmark-user";
    private static final String BENCHMARK_PASSWORD = "benchmark-password";

    /** Keycloak capabilities shared by integration/benchmark realms. */
    private static final Set<Capability> KEYCLOAK_CAPABILITIES =
            EnumSet.of(Capability.ROLES, Capability.GROUPS, Capability.CUSTOM_SCOPES, Capability.JWT_ACCESS_TOKENS);

    // Zitadel connection constants (HTTP — tlsMode=external, tokens have https issuer)
    private static final String ZITADEL_BASE_URL = "http://localhost:3080";
    private static final String ZITADEL_TOKEN_ENDPOINT = "/oauth/v2/token";

    /** Path to credentials file generated by the Zitadel setup script. */
    private static final Path ZITADEL_CREDENTIALS_PATH = Path.of("target/zitadel-credentials.properties");

    /**
     * Zitadel capabilities — JWT access tokens only for now.
     * Zitadel Actions v1 don't populate user grants in client_credentials flow,
     * so roles/groups claims cannot be injected. This limits Zitadel to token
     * validation and string return tests. Roles/groups support requires Zitadel
     * Actions v2 or a different token acquisition flow (e.g. authorization_code).
     */
    private static final Set<Capability> ZITADEL_CAPABILITIES =
            EnumSet.of(Capability.JWT_ACCESS_TOKENS);

    /** Default scopes for providers that don't specify their own. */
    private static final String DEFAULT_SCOPES = "openid profile email";

    private final String realmIdentifier;
    private final String clientId;
    private final String clientSecret;
    private final String baseUrl;
    private final String tokenEndpoint;
    private final String providerName;
    private final Set<Capability> capabilities;
    private final String defaultScopes;
    private final TokenAcquisitionStrategy tokenStrategy;

    /** ROPC constructor — creates a {@link RopcStrategy} from username/password. */
    private TestRealm(String realmIdentifier, String clientId, String clientSecret,
                      String username, String password, String baseUrl,
                      String tokenEndpoint, String providerName,
                      Set<Capability> capabilities) {
        this(realmIdentifier, clientId, clientSecret, baseUrl, tokenEndpoint, providerName,
                capabilities, DEFAULT_SCOPES, new RopcStrategy(username, password));
    }

    /** ROPC constructor with custom default scopes. */
    private TestRealm(String realmIdentifier, String clientId, String clientSecret,
                      String username, String password, String baseUrl,
                      String tokenEndpoint, String providerName,
                      Set<Capability> capabilities, String defaultScopes) {
        this(realmIdentifier, clientId, clientSecret, baseUrl, tokenEndpoint, providerName,
                capabilities, defaultScopes, new RopcStrategy(username, password));
    }

    /** General constructor with explicit token acquisition strategy. */
    private TestRealm(String realmIdentifier, String clientId, String clientSecret,
                      String baseUrl, String tokenEndpoint, String providerName,
                      Set<Capability> capabilities, String defaultScopes,
                      TokenAcquisitionStrategy tokenStrategy) {
        this.realmIdentifier = realmIdentifier;
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.baseUrl = baseUrl;
        this.tokenEndpoint = tokenEndpoint;
        this.providerName = providerName;
        this.capabilities = EnumSet.copyOf(capabilities);
        this.defaultScopes = defaultScopes;
        this.tokenStrategy = tokenStrategy;
    }

    /**
     * Returns the provider name for display in test output.
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * Returns whether this realm supports the given capability.
     */
    public boolean hasCapability(Capability capability) {
        return capabilities.contains(capability);
    }

    /**
     * Returns whether this realm supports <em>all</em> of the given capabilities.
     */
    public boolean hasAllCapabilities(Capability... required) {
        return capabilities.containsAll(Set.of(required));
    }

    /**
     * Returns the immutable set of capabilities this realm supports.
     */
    public Set<Capability> getCapabilities() {
        return Set.copyOf(capabilities);
    }

    // === Factory methods ===

    public static TestRealm createIntegrationRealm() {
        return new TestRealm(
                INTEGRATION_REALM_ID, INTEGRATION_CLIENT_ID, INTEGRATION_CLIENT_SECRET,
                INTEGRATION_USERNAME, INTEGRATION_PASSWORD,
                KEYCLOAK_BASE_URL, TOKEN_ENDPOINT_TEMPLATE.formatted(INTEGRATION_REALM_ID),
                "Keycloak", KEYCLOAK_CAPABILITIES);
    }

    /**
     * DPoP testing — uses {@code dpop-client} in the integration realm
     * with {@code dpop.bound.access.tokens=true}.
     */
    public static TestRealm createDpopRealm() {
        return new TestRealm(
                INTEGRATION_REALM_ID, DPOP_CLIENT_ID, DPOP_CLIENT_SECRET,
                INTEGRATION_USERNAME, INTEGRATION_PASSWORD,
                KEYCLOAK_BASE_URL, TOKEN_ENDPOINT_TEMPLATE.formatted(INTEGRATION_REALM_ID),
                "Keycloak", KEYCLOAK_CAPABILITIES);
    }

    /**
     * JWE testing — uses {@code jwe-client} in the integration realm
     * with encrypted ID token response configured.
     */
    public static TestRealm createJweRealm() {
        return new TestRealm(
                INTEGRATION_REALM_ID, JWE_CLIENT_ID, JWE_CLIENT_SECRET,
                INTEGRATION_USERNAME, INTEGRATION_PASSWORD,
                KEYCLOAK_BASE_URL, TOKEN_ENDPOINT_TEMPLATE.formatted(INTEGRATION_REALM_ID),
                "Keycloak", KEYCLOAK_CAPABILITIES);
    }

    public static TestRealm createBenchmarkRealm() {
        return new TestRealm(
                BENCHMARK_REALM_ID, BENCHMARK_CLIENT_ID, BENCHMARK_CLIENT_SECRET,
                BENCHMARK_USERNAME, BENCHMARK_PASSWORD,
                KEYCLOAK_BASE_URL, TOKEN_ENDPOINT_TEMPLATE.formatted(BENCHMARK_REALM_ID),
                "Keycloak", KEYCLOAK_CAPABILITIES);
    }

    /**
     * Dex — lightweight, OpenID Certified provider for multi-IDP validation.
     * <p>
     * Access tokens are valid JWTs (RS256-signed) but do not include a {@code scope}
     * claim, which is optional per RFC 9068 Section 2.2.
     * <p>
     * Dex supports {@code groups} natively (via static user config + {@code groups}
     * scope) but does not support custom scopes (rejects unknown scopes with 400)
     * or arbitrary custom claims like {@code roles} in the local connector.
     */
    public static TestRealm createDexProvider() {
        return new TestRealm(
                "dex", "dex-client", "dex-secret",
                "dex-user@example.com", "dex-password",
                "https://localhost:2556", "/dex/token",
                "Dex",
                EnumSet.of(Capability.OFFLINE_ACCESS, Capability.JWT_ACCESS_TOKENS, Capability.GROUPS),
                "openid profile email groups");
    }

    /**
     * Zitadel — full-featured OIDC provider for multi-IDP bearer auth testing.
     * <p>
     * Uses RFC 8693 Token Exchange instead of ROPC (which Zitadel does not support).
     * Credentials are dynamically generated by the setup script and read from
     * {@code target/zitadel-credentials.properties}.
     * <p>
     * Zitadel supports roles (via project role grants) and groups (via Actions
     * injecting user metadata) but does not support custom scopes beyond standard
     * OIDC and its own URN-based scopes.
     */
    public static TestRealm createZitadelProvider() {
        Properties credentials = loadZitadelCredentials();

        String serviceUserId = credentials.getProperty("zitadel.service.client-id");
        String serviceUserSecret = credentials.getProperty("zitadel.service.client-secret");
        String projectId = credentials.getProperty("zitadel.project.id");

        // client_credentials with service account (machine user) credentials
        var strategy = new TokenExchangeStrategy(serviceUserId, serviceUserSecret);

        // Include project audience scope; openid scope triggers id_token which may have
        // different signing keys than access_token (key rotation timing), so omit it
        String defaultScopes = "profile email urn:zitadel:iam:org:project:id:" + projectId + ":aud";

        return new TestRealm(
                "zitadel", serviceUserId, serviceUserSecret,
                ZITADEL_BASE_URL, ZITADEL_TOKEN_ENDPOINT,
                "Zitadel", ZITADEL_CAPABILITIES,
                defaultScopes,
                strategy);
    }

    private static Properties loadZitadelCredentials() {
        var properties = new Properties();
        try (var reader = Files.newBufferedReader(ZITADEL_CREDENTIALS_PATH)) {
            properties.load(reader);
        } catch (IOException e) {
            throw new IllegalStateException(
                    "Failed to load Zitadel credentials from " + ZITADEL_CREDENTIALS_PATH
                            + ". Ensure the Zitadel setup script has run successfully.", e);
        }
        return properties;
    }

    // === Token acquisition ===

    /**
     * Obtains a valid token with the provider's default scopes.
     * <p>
     * Default scopes are provider-specific because IDPs reject unrecognized scopes
     * (e.g., Dex supports {@code groups} but not {@code read}; Keycloak requires
     * scopes to be registered as client scopes).
     */
    public TokenResponse obtainValidToken() {
        return obtainValidTokenWithScopes(defaultScopes);
    }

    /**
     * Obtains a valid token with specific scopes.
     * Delegates to the configured {@link TokenAcquisitionStrategy}.
     */
    public TokenResponse obtainValidTokenWithScopes(String scopes) {
        TokenResponse response = tokenStrategy.acquireToken(
                baseUrl, tokenEndpoint, clientId, clientSecret, scopes);

        validateToken(response.accessToken(), "Access token from " + this);
        // ID token is not returned by client_credentials grant (Zitadel)
        if (response.idToken() != null) {
            validateToken(response.idToken(), "ID token from " + this);
        }
        if (response.refreshToken() != null) {
            validateToken(response.refreshToken(), "Refresh token from " + this);
        }

        return response;
    }

    /**
     * Obtains a valid token with all required scopes for bearer token tests.
     * Includes the "read" scope required by the BearerToken annotations.
     */
    public TokenResponse obtainValidTokenWithAllScopes() {
        return obtainValidTokenWithScopes("openid profile email read");
    }

    /**
     * Obtains a DPoP-bound token by sending a DPoP proof header with the token request.
     * The returned access token will contain a {@code cnf.jkt} claim.
     * <p>
     * DPoP requires ROPC — only supported by Keycloak realms.
     *
     * @throws IllegalStateException if this realm does not use {@link RopcStrategy}
     */
    public TokenResponse obtainDpopBoundToken(DpopProofHelper dpopHelper) {
        if (!(tokenStrategy instanceof RopcStrategy ropc)) {
            throw new IllegalStateException(
                    "DPoP token acquisition requires ROPC strategy, but " + this
                            + " uses " + tokenStrategy.getClass().getSimpleName());
        }

        String tokenUrl = baseUrl + tokenEndpoint;
        String dpopProof = dpopHelper.createTokenEndpointProof(tokenUrl);

        Response tokenResponse = given()
                .baseUri(baseUrl)
                .contentType("application/x-www-form-urlencoded")
                .header("DPoP", dpopProof)
                .formParam("client_id", clientId)
                .formParam("client_secret", clientSecret)
                .formParam("username", ropc.getUsername())
                .formParam("password", ropc.getPassword())
                .formParam("grant_type", "password")
                .formParam("scope", "openid profile email")
                .when()
                .post(tokenEndpoint);

        assertEquals(200, tokenResponse.statusCode(),
                "Should be able to obtain DPoP-bound tokens from " + this
                        + ". Response: " + tokenResponse.body().asString());

        Map<String, Object> tokenData = tokenResponse.jsonPath().getMap("");

        String accessToken = (String) tokenData.get("access_token");
        String idToken = (String) tokenData.get("id_token");
        String refreshToken = (String) tokenData.get("refresh_token");

        validateToken(accessToken, "DPoP-bound access token");
        validateToken(idToken, "ID token");
        validateToken(refreshToken, "Refresh token");

        return new TokenResponse(accessToken, idToken, refreshToken);
    }

    @Override
    public String toString() {
        return providerName + "/" + realmIdentifier;
    }

    private void validateToken(String token, String tokenType) {
        assertNotNull(token, tokenType + " should not be null");
        assertFalse(token.isEmpty(), tokenType + " should not be empty");
    }

    /**
     * Response object containing the different token types.
     */
    public record TokenResponse(String accessToken, String idToken, String refreshToken) {
    }
}
