/*
 * Copyright © 2025 CUI-OpenSource-Software (info@cuioss.de)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.cuioss.sheriff.token.quarkus.jwe;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.security.GeneralSecurityException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.RSAPrivateKey;
import java.security.spec.ECGenParameterSpec;
import java.util.Base64;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("DecryptionKeyLoader Tests")
class DecryptionKeyLoaderTest {

    @TempDir
    Path tempDir;

    @Test
    @DisplayName("Should load RSA private key from PEM file")
    void shouldLoadRsaKeyFromPem() throws Exception {
        KeyPair keyPair = generateRsaKeyPair();
        Path pemFile = writePemFile(keyPair.getPrivate(), "rsa-key.pem");

        PrivateKey loaded = DecryptionKeyLoader.loadFromPem(pemFile);

        assertNotNull(loaded);
        assertInstanceOf(RSAPrivateKey.class, loaded);
        assertEquals(keyPair.getPrivate(), loaded);
    }

    @Test
    @DisplayName("Should load EC private key from PEM file")
    void shouldLoadEcKeyFromPem() throws Exception {
        KeyPair keyPair = generateEcKeyPair();
        Path pemFile = writePemFile(keyPair.getPrivate(), "ec-key.pem");

        PrivateKey loaded = DecryptionKeyLoader.loadFromPem(pemFile);

        assertNotNull(loaded);
        assertInstanceOf(ECPrivateKey.class, loaded);
        assertEquals(keyPair.getPrivate(), loaded);
    }

    @Test
    @DisplayName("Should reject non-PKCS8 PEM content")
    void shouldRejectNonPkcs8Pem() throws Exception {
        Path pemFile = tempDir.resolve("bad-key.pem");
        Files.writeString(pemFile, "-----BEGIN RSA PRIVATE KEY-----\nMIIBog==\n-----END RSA PRIVATE KEY-----");

        assertThrows(IllegalArgumentException.class, () -> DecryptionKeyLoader.loadFromPem(pemFile));
    }

    @Test
    @DisplayName("Should throw for nonexistent PEM file")
    void shouldThrowForMissingFile() {
        Path missing = tempDir.resolve("nonexistent.pem");

        assertThrows(IllegalStateException.class, () -> DecryptionKeyLoader.loadFromPem(missing));
    }

    @Test
    @DisplayName("Should load key from PKCS12 keystore generated by keytool")
    void shouldLoadKeyFromPkcs12() throws Exception {
        Path keystorePath = tempDir.resolve("keystore.p12");
        String alias = "test-alias";
        String storePass = "storepass";

        // Generate keystore using keytool (JDK tool, always available)
        ProcessBuilder pb = new ProcessBuilder(
                "keytool", "-genkeypair",
                "-alias", alias,
                "-keyalg", "RSA",
                "-keysize", "2048",
                "-validity", "1",
                "-dname", "CN=Test",
                "-storetype", "PKCS12",
                "-keystore", keystorePath.toString(),
                "-storepass", storePass,
                "-keypass", storePass);
        pb.redirectErrorStream(true);
        Process process = pb.start();
        int exitCode = process.waitFor();
        assertEquals(0, exitCode, "keytool should succeed: " + new String(process.getInputStream().readAllBytes()));

        PrivateKey loaded = DecryptionKeyLoader.loadFromKeyStore(
                keystorePath,
                storePass.toCharArray(),
                alias,
                storePass.toCharArray());

        assertNotNull(loaded);
        assertInstanceOf(RSAPrivateKey.class, loaded);
    }

    @Test
    @DisplayName("Should throw for wrong alias in keystore")
    void shouldThrowForMissingAlias() throws Exception {
        Path keystorePath = tempDir.resolve("keystore2.p12");
        String storePass = "storepass";

        ProcessBuilder pb = new ProcessBuilder(
                "keytool", "-genkeypair",
                "-alias", "real-alias",
                "-keyalg", "RSA",
                "-keysize", "2048",
                "-validity", "1",
                "-dname", "CN=Test",
                "-storetype", "PKCS12",
                "-keystore", keystorePath.toString(),
                "-storepass", storePass,
                "-keypass", storePass);
        pb.redirectErrorStream(true);
        Process process = pb.start();
        assertEquals(0, process.waitFor());

        var storePassChars = storePass.toCharArray();
        var wrongAlias = "wrong-alias";
        assertThrows(IllegalArgumentException.class, () ->
                DecryptionKeyLoader.loadFromKeyStore(
                        keystorePath,
                        storePassChars,
                        wrongAlias,
                        storePassChars));
    }

    @Test
    @DisplayName("Should parse PEM content directly")
    void shouldParsePemContent() throws Exception {
        KeyPair keyPair = generateRsaKeyPair();
        String pem = "-----BEGIN PRIVATE KEY-----\n"
                + Base64.getMimeEncoder(64, "\n".getBytes())
                .encodeToString(keyPair.getPrivate().getEncoded())
                + "\n-----END PRIVATE KEY-----\n";

        PrivateKey loaded = DecryptionKeyLoader.parsePemContent(pem);

        assertNotNull(loaded);
        assertEquals(keyPair.getPrivate(), loaded);
    }

    @Test
    @DisplayName("Should throw with suppressed RSA exception when both RSA and EC parsing fail")
    void shouldThrowWithSuppressedExceptionForCorruptedKey() {
        // Create corrupted PKCS8 data that is valid base64 but not a valid key for RSA or EC
        byte[] corruptedKeyBytes = new byte[]{0x30, 0x0D, 0x06, 0x09, 0x2A, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF};
        String corruptedPem = "-----BEGIN PRIVATE KEY-----\n"
                + Base64.getMimeEncoder(64, "\n".getBytes()).encodeToString(corruptedKeyBytes)
                + "\n-----END PRIVATE KEY-----\n";

        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> DecryptionKeyLoader.parsePemContent(corruptedPem)
        );

        // Verify the exception message indicates failure
        assertTrue(exception.getMessage().contains("not RSA or EC"),
                "Exception message should indicate both RSA and EC parsing failed");

        // Verify the RSA exception is attached as suppressed on the cause
        Throwable cause = exception.getCause();
        assertNotNull(cause, "Should have a cause from EC parsing failure");
        assertEquals(1, cause.getSuppressed().length,
                "EC exception should have RSA exception as suppressed");
    }

    @Test
    @DisplayName("Should parse EC key via RSA-first-then-EC fallback path")
    void shouldParseEcKeyViaFallbackPath() throws Exception {
        // EC key will fail RSA parsing first, then succeed as EC
        KeyPair ecKeyPair = generateEcKeyPair();
        String ecPem = "-----BEGIN PRIVATE KEY-----\n"
                + Base64.getMimeEncoder(64, "\n".getBytes())
                .encodeToString(ecKeyPair.getPrivate().getEncoded())
                + "\n-----END PRIVATE KEY-----\n";

        PrivateKey loaded = DecryptionKeyLoader.parsePemContent(ecPem);

        assertNotNull(loaded);
        assertInstanceOf(ECPrivateKey.class, loaded);
        assertEquals(ecKeyPair.getPrivate(), loaded);
    }

    private KeyPair generateRsaKeyPair() throws GeneralSecurityException {
        KeyPairGenerator gen = KeyPairGenerator.getInstance("RSA");
        gen.initialize(2048);
        return gen.generateKeyPair();
    }

    private KeyPair generateEcKeyPair() throws GeneralSecurityException {
        KeyPairGenerator gen = KeyPairGenerator.getInstance("EC");
        gen.initialize(new ECGenParameterSpec("secp256r1"));
        return gen.generateKeyPair();
    }

    private Path writePemFile(PrivateKey key, String filename) throws Exception {
        Path pemFile = tempDir.resolve(filename);
        String pem = "-----BEGIN PRIVATE KEY-----\n"
                + Base64.getMimeEncoder(64, "\n".getBytes()).encodeToString(key.getEncoded())
                + "\n-----END PRIVATE KEY-----\n";
        Files.writeString(pemFile, pem);
        return pemFile;
    }
}
