/*
 * Copyright © 2022 CUI-OpenSource-Software (info@cuioss.de)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.cuioss.sheriff.token.client.flow;

import de.cuioss.sheriff.token.client.auth.ClientSecretBasicAuth;
import de.cuioss.sheriff.token.client.config.ClientAuthMethod;
import de.cuioss.sheriff.token.client.config.ClientConfiguration;
import de.cuioss.sheriff.token.client.discovery.ProviderMetadata;
import de.cuioss.sheriff.token.client.token.IdTokenValidationBridge;
import de.cuioss.sheriff.token.client.token.TokenValidationBridge;
import de.cuioss.sheriff.token.validation.TokenValidator;
import de.cuioss.sheriff.token.validation.test.TestTokenHolder;
import de.cuioss.sheriff.token.validation.test.generator.TestTokenGenerators;
import de.cuioss.test.generator.Generators;
import de.cuioss.test.mockwebserver.URIBuilder;
import de.cuioss.test.mockwebserver.dispatcher.HttpMethodMapper;
import de.cuioss.test.mockwebserver.dispatcher.ModuleDispatcherElement;
import lombok.Getter;
import mockwebserver3.MockResponse;
import mockwebserver3.RecordedRequest;
import okhttp3.Headers;
import org.junit.jupiter.api.function.Executable;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Shared base for the <em>wired-flow</em> test tier ({@code S0}): it assembles and drives the real
 * flow orchestrators ({@link AuthorizationCodeFlow}, {@link RefreshFlow}, {@link StepUpHandler})
 * exactly as an application would, so a defence's absence from the executable path is observable —
 * not merely as a component unit-test that never reaches the orchestrator, but as a recorded
 * token-endpoint call-count.
 * <p>
 * The verification strategy this tier closes is the root cause named in the code review: every
 * security component is unit-tested in isolation, but nothing asserted that the engine's own flow
 * orchestrator, called end to end, actually runs the check. A subclass drives the assembled flow
 * against the {@link RecordingTokenEndpointDispatcher} and asserts, via
 * {@link #assertRefusedBeforeTokenEndpoint(Class, Executable)}, that a rejected request never reaches
 * the token endpoint (call-count {@code == 0}) — so deleting the defence from the wired path fails the
 * test.
 * <p>
 * The dispatcher serves <em>real</em>, pipeline-validatable JWTs generated by
 * {@link TestTokenGenerators}, because a guarded exchange validates the retrieved tokens; the fixed
 * non-JWT bodies of the commons token dispatcher cannot drive a validated exchange, so this tier
 * provides its own recording dispatcher.
 * <p>
 * Subclasses call {@link #initWiredFlow()} from their {@code @BeforeEach} and expose the dispatcher to
 * {@code @EnableMockWebServer} through the inherited {@link #getModuleDispatcher()} accessor.
 */
abstract class WiredFlowTestSupport {

    /** The issuer the assembled configuration and provider metadata are bound to. */
    protected static final String ISSUER = "https://issuer.example.com";

    /** The single, exact redirect URI the interactive flow is registered with. */
    protected static final String REDIRECT_URI = "https://rp.example.com/callback";

    @Getter
    private final RecordingTokenEndpointDispatcher moduleDispatcher = new RecordingTokenEndpointDispatcher();

    /** The generated access-token holder; its issuer config backs the validator. */
    protected TestTokenHolder accessHolder;

    /** The generated ID-token holder; validated against the same validator. */
    protected TestTokenHolder idHolder;

    /** The access-token validation bridge assembled over the shared validator. */
    protected TokenValidationBridge accessBridge;

    /** The ID-token validation bridge assembled over the shared validator. */
    protected IdTokenValidationBridge idBridge;

    /**
     * Generates fresh access/ID token holders, assembles the validation bridges over a validator
     * bound to the generated issuer, and resets the recording dispatcher. Subclasses invoke this from
     * their {@code @BeforeEach}.
     */
    protected void initWiredFlow() {
        accessHolder = TestTokenGenerators.accessTokens().next();
        idHolder = TestTokenGenerators.idTokens().next();
        TokenValidator validator = TokenValidator.builder().issuerConfig(accessHolder.getIssuerConfig()).build();
        accessBridge = new TokenValidationBridge(validator);
        idBridge = new IdTokenValidationBridge(validator);
        moduleDispatcher.reset();
    }

    /**
     * @return a shared-secret ({@code client_secret_basic}) client configuration bound to the test
     *         issuer, cleartext-permitted for the mock server
     */
    protected static ClientConfiguration config() {
        return ClientConfiguration.builder()
                .issuer(ISSUER)
                .clientId(Generators.nonBlankStrings().next())
                .clientSecret(Generators.nonBlankStrings().next())
                .authMethod(ClientAuthMethod.CLIENT_SECRET_BASIC)
                .scope("openid")
                .redirectUri(REDIRECT_URI)
                .allowInsecureHttp(true)
                .build();
    }

    /**
     * @param uriBuilder the mock-server URI builder injected by {@code @EnableMockWebServer}
     * @return provider metadata whose token endpoint targets the mock server's {@code /token} path
     */
    protected static ProviderMetadata metadataWithTokenEndpoint(URIBuilder uriBuilder) {
        var metadata = new ProviderMetadata();
        metadata.issuer = ISSUER;
        metadata.tokenEndpoint = uriBuilder.addPathSegment("token").buildAsString();
        return metadata;
    }

    /**
     * Assembles the {@code authorization_code} flow exactly as the CDI producer does — over the
     * configuration, a fresh token-endpoint transport, and the shared validation bridges.
     *
     * @param config the client configuration
     * @return the wired authorization-code flow
     */
    protected AuthorizationCodeFlow authorizationCodeFlow(ClientConfiguration config) {
        return new AuthorizationCodeFlow(config, new TokenEndpointClient(config), accessBridge, idBridge);
    }

    /**
     * Assembles the {@code refresh_token} flow exactly as the CDI producer does.
     *
     * @param config the client configuration
     * @return the wired refresh flow
     */
    protected RefreshFlow refreshFlow(ClientConfiguration config) {
        return new RefreshFlow(config, new TokenEndpointClient(config), accessBridge, clientAuth(config));
    }

    /**
     * @return a step-up handler with its default authorization-request builder
     */
    protected StepUpHandler stepUpHandler() {
        return new StepUpHandler();
    }

    /**
     * @param config the client configuration
     * @return the shared-secret client authentication for {@code config}
     */
    protected static ClientSecretBasicAuth clientAuth(ClientConfiguration config) {
        return new ClientSecretBasicAuth(config.getClientId(), config.getClientSecret());
    }

    /**
     * Asserts that a wired-flow action is refused <em>before any side effect</em>: it throws the
     * expected exception AND the token endpoint was never called. This is the core wired-flow
     * assertion — a defence that only rejects <em>after</em> redeeming the code, or one deleted from
     * the executable path, fails here because the recorded call-count is non-zero.
     *
     * @param expected the exception type the guarded refusal must raise
     * @param action   the wired-flow invocation expected to be refused
     * @param <T>      the expected throwable type
     */
    protected <T extends Throwable> void assertRefusedBeforeTokenEndpoint(Class<T> expected, Executable action) {
        assertThrows(expected, action);
        getModuleDispatcher().assertNotCalled();
    }

    /**
     * Recording token-endpoint dispatcher: serves a configurable, pipeline-validatable token response
     * (or an error) and records how many times the token endpoint was actually called, so a
     * wired-flow test can assert a rejected request never reached it.
     */
    static final class RecordingTokenEndpointDispatcher implements ModuleDispatcherElement {

        private static final int HTTP_OK = 200;
        private static final int HTTP_BAD_REQUEST = 400;
        private static final String DPOP_HEADER = "DPoP";
        private static final String DPOP_NONCE_HEADER = "DPoP-Nonce";

        private int status = HTTP_OK;
        private String body = "";

        /** The {@code DPoP} proof header recorded for each token-endpoint call, in call order. */
        private final List<String> recordedDpopHeaders = new ArrayList<>();

        /**
         * When non-{@code null}, the next call is answered with a {@code use_dpop_nonce} challenge
         * (HTTP 400 carrying this {@code DPoP-Nonce}) exactly once; the challenge is then consumed and
         * subsequent calls serve the configured success/error body (RFC 9449 §8).
         */
        private String pendingNonceChallenge;

        @Getter
        private int callCount;

        void reset() {
            this.status = HTTP_OK;
            this.body = "";
            this.callCount = 0;
            this.recordedDpopHeaders.clear();
            this.pendingNonceChallenge = null;
        }

        /**
         * Arms a one-shot {@code use_dpop_nonce} challenge: the first token-endpoint call is refused
         * with HTTP 400 and the given {@code DPoP-Nonce}, so the DPoP-aware transport must retry with a
         * nonce-bound proof. Configure the eventual success body via {@link #success} first.
         *
         * @param nonce the {@code DPoP-Nonce} to challenge with; echoed by a compliant client's retry
         */
        void challengeWithNonceOnce(String nonce) {
            this.pendingNonceChallenge = nonce;
        }

        /**
         * @return the {@code DPoP} proof header recorded on the most recent token-endpoint call, or
         *         {@code null} when the last call carried no DPoP header
         */
        String lastRecordedDpopHeader() {
            return recordedDpopHeaders.isEmpty() ? null : recordedDpopHeaders.getLast();
        }

        void success(String accessToken, String idToken, String refreshToken, long expiresIn) {
            this.status = HTTP_OK;
            StringBuilder json = new StringBuilder("{\"access_token\":\"").append(accessToken)
                    .append("\",\"token_type\":\"Bearer\",\"expires_in\":").append(expiresIn);
            if (idToken != null) {
                json.append(",\"id_token\":\"").append(idToken).append('"');
            }
            if (refreshToken != null) {
                json.append(",\"refresh_token\":\"").append(refreshToken).append('"');
            }
            json.append('}');
            this.body = json.toString();
        }

        void error() {
            this.status = HTTP_BAD_REQUEST;
            this.body = "{\"error\":\"invalid_grant\"}";
        }

        @Override
        public String getBaseUrl() {
            return "/token";
        }

        @Override
        public Set<HttpMethodMapper> supportedMethods() {
            return Set.of(HttpMethodMapper.POST);
        }

        @Override
        public Optional<MockResponse> handlePost(RecordedRequest request) {
            callCount++;
            recordedDpopHeaders.add(request.getHeaders().get(DPOP_HEADER));
            if (pendingNonceChallenge != null) {
                String challenge = pendingNonceChallenge;
                pendingNonceChallenge = null;
                return Optional.of(new MockResponse(HTTP_BAD_REQUEST,
                        Headers.of("Content-Type", "application/json", DPOP_NONCE_HEADER, challenge),
                        "{\"error\":\"use_dpop_nonce\"}"));
            }
            return Optional.of(new MockResponse(status, Headers.of("Content-Type", "application/json"), body));
        }

        void assertNotCalled() {
            assertEquals(0, callCount,
                    "the request must be refused before any token-endpoint call (call-count must be 0)");
        }

        void assertCalled(int expected) {
            assertEquals(expected, callCount, "unexpected token-endpoint call-count");
        }
    }
}
