# Runs E2E Playwright tests for Dev-UI components via Maven with report deployment.
name: End-to-End Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e-tests:
    uses: cuioss/cuioss-organization/.github/workflows/reusable-maven-integration-tests.yml@a7368d92f50df26ff8e495b9bd8ecee4cf9a8471 # v0.6.7
    with:
      report-name: e-2-e-playwright
      maven-args-input: |
        install -DskipTests -T 1C -pl bom,oauth-sheriff-core,oauth-sheriff-quarkus-parent,oauth-sheriff-quarkus-parent/oauth-sheriff-quarkus,oauth-sheriff-quarkus-parent/oauth-sheriff-quarkus-deployment,oauth-sheriff-quarkus-parent/oauth-sheriff-quarkus-integration-tests
        verify -Pe2e-tests -pl oauth-sheriff-quarkus-parent/e-2-e-playwright
      install-playwright: true
      npm-cache: true
      timeout-minutes: 30
      reports-folder: |
        oauth-sheriff-quarkus-parent/e-2-e-playwright/target/test-results
      report-logs: |
        oauth-sheriff-quarkus-parent/e-2-e-playwright/target/quarkus-dev.log
    secrets:
      RELEASE_APP_ID: ${{ secrets.RELEASE_APP_ID }}
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
